language: python

branches:
  only:
    - master

env:
  - TOXENV=py32,py33,py34,pypy3
  - TOXENV=flake8,docs
  - TOXENV=coverage

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - if [ "$TOXENV" = "coverage" ]; then coveralls; fi
