language: python

branches:
  only:
    - master

env:
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy3
  - TOXENV=docs
  - TOXENV=flake8

install:
  - pip install tox

script:
  - tox

after_success:
  # integrate coveralls
  - pip install pytest-cov python-coveralls
  - py.test tests/ --cov dooku/
  - coveralls
